---
- name: Include OS specific variables
  ansible.builtin.include_vars:
    file: "{{ ansible_os_family | lower }}.yml"

- name: Disable Root Login
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: ^(#?PermitRootLogin)+\s*
    line: "PermitRootLogin no"
    state: present
    backup: true
  become: true
  notify:
    - restart_ssh

- name: Add hosts
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "0644"
  loop: "{{ setup_templates }}"

- name: Install needed packages
  when: ansible_distribution
  ansible.builtin.package:
    name: "{{ setup_packages }}"
    state: present

- name: Include tasks for Redhat distros
  when: ansible_os_family == 'RedHat'
  ansible.builtin.include_tasks: redhat.yml

# - name: Include tasks for Debian distros
#   when: ansible_os_family == 'Debian'
#   ansible.builtin.include_tasks: debian.yml

- name: Create groups
  ansible.builtin.group:
    name: "{{ item.name }}"
    gid: "{{ item.gid | default(omit) }}"
  loop: "{{ setup_groups }}"

- name: Include Tasks for user
  ansible.builtin.include_tasks: users.yml
  loop: "{{ setup_users }}"
