---
- name: Create Users
  ansible.builtin.user:
    name: "{{ item.name }}"
    uid: "{{ item.user_id }}"
    group: "{{ item.main_group }}"
    groups: "{{ item.group_list | default(omit) }}"
    shell: "{{ item.shell | default(omit) }}"
    password: "{{ item.password | default(omit) }}"

- name: Set authorized keys
  when:
    - item.authorized_keys is defined
    - item.authorized_keys | length > 0
  ansible.posix.authorized_key:
    user: "{{ item.name }}"
    state: present
    key: "{{ key_item }}"
  loop: "{{ item.authorized_keys }}"
  # I have to create new loop_var because item is taken by upstream loop -> main.yml : loop: "{{ setup_groups }}" include tasks step
  loop_control:
    loop_var: key_item

- name: Add user to sudoers
  when:
    - item.sudo | default(false) | bool
  ansible.builtin.copy:
    dest: "/etc/sudoers.d/{{ item.name }}"
    content: "{{ item.name }} ALL=(ALL) NOPASSWD: ALL"
    owner: root
    group: root
    mode: "0440"
